### ISSUE TITLE
Review request

### ISSUE THREAD

**Issue by jeetiss** [jeetiss/callbag-marble-tester#1]
@Andarist 

would love review of this code 🙃

**Comment by Andarist** [comment]
Looks cool! I would maybe change the name of the package to `callbag-marble-tester` or something as this is similar to what Rx uses https://github.com/ReactiveX/rxjs/blob/master/doc/internal-marble-tests.md and they call it marble tests, but in terms of the code it doesn't matter.

I'll review the code some time later, thanks for pinging me about this!

**Comment by Andarist** [comment]
Sorry that I haven't reviewed this yet, couldn't find time to do it. I definitely want to come back to it when I get some free time.

**Comment by anilanar** [comment]
I think relying on real time for frames doesn't always work although I didn't dive into might be going wrong. E.g. the following fails:

```
  pipe(
    combine(
      listenable('-a|', { a: 1 }),
      pullable('(b|)', {b: 2})
    ),
    willBe('-a|', { a: [1, 2] }),

    // if you use the following line it will work:
    // willBe('a|', { a: [1, 2] }),
  ));
```

**Comment by anilanar** [comment]
When a test fails, the output string is quite uninformative in its current state. You usually get something like:

```
    Failed: "
    expected: -a
    received: -a

    "
```
